apps/share/urls.py
from django.conf.urls import patterns, url
from apps.share import views

urlpatterns = patterns('',
                       url(r'^$', views.lesson),
                       url(r'^lesson/$', views.lesson),
                       url(r'^lesson/child/(?P<parent_id>[\d]+?)$',views.child_lesson),
                       url(r'^exercise/$', views.exercise),
                       url(r'^datum/$', views.doc),
                       url(r'^datum/doc/$', views.doc),
                       url(r'^datum/frame/$', views.frame),
                       url(r'^datum/frame/article$', views.article),
                       url(r'^downloads/$', views.downloads),
                       )

bnu/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.views.generic import TemplateView
from bnu.views import index
from django.conf import settings

from adminplus.sites import AdminSitePlus

admin.site = AdminSitePlus()
admin.autodiscover()


urlpatterns = [
    url(r'^!bnu404~', include(admin.site.urls)),
    url(r'^$', index, name='index'),
    url(r'^index$', index),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^practice/', include('apps.practice.urls')),
    url(r'^trade/', include('apps.trade.urls')),
    url(r'^share/', include('apps.share.urls')),
    url(r'^uploads$', include('apps.uploads.urls')),
    url(
        r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.MEDIA_ROOT}
    ),
    url(
        r'^static/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}
    )
]

if settings.DEBUG:
    urlpatterns += patterns(
        '',
        url(r'^403', TemplateView.as_view(template_name='403.html')),
        url(r'^404', TemplateView.as_view(template_name='404.html')),
        url(r'^500', TemplateView.as_view(template_name='500.html')),
    )

apps/lessons/models.py
from django.db import models

# Create your models here.

apps/share/models.py
# coding: utf-8
from django.db import models
import os

# Create your models here.


class ParentLessons(models.Model):

    title = models.CharField(max_length=50, verbose_name=u'标题')
    image = models.ImageField(
        upload_to='images/', verbose_name=u'课程封面图', null=True
    )
    description = models.CharField(max_length=255, verbose_name=u'课程描述')
    submit_time = models.DateTimeField(auto_now_add=True, verbose_name=u"添加时间")
    update_time = models.DateTimeField(auto_now_add=True, verbose_name=u"修改时间")

    def __unicode__(self):
        return '%s' % self.title

    class Meta:
        verbose_name_plural = '主课程'


class ChildLessons(models.Model):

    parent = models.ForeignKey(ParentLessons)
    title = models.CharField(max_length=50, verbose_name=u'标题')
    link = models.CharField(max_length=255, verbose_name=u'网课链接')
    submit_time = models.DateTimeField(auto_now_add=True, verbose_name=u"添加时间")
    update_time = models.DateTimeField(auto_now_add=True, verbose_name=u"修改时间")

    def __unicode__(self):
        return '%s' % self.title

    class Meta:
        verbose_name_plural = '子课程'


class Downloads(models.Model):
    title = models.CharField(max_length=50, verbose_name=u'文件标题')
    name = models.FileField(
        upload_to='downloads/',
        max_length=255, blank=False
    )
    link = models.CharField(max_length=255, blank=True)
    submit_time = models.DateTimeField(auto_now_add=True, verbose_name=u"添加时间")
    update_time = models.DateTimeField(auto_now_add=True, verbose_name=u"修改时间")

    def __unicode__(self):
        return '%s' % self.name

    def save(self, *args, **kwargs):
        super(self.__class__, self).save(*args, **kwargs)
        Downloads.objects.filter(id=self.id).update(
            link=os.path.join('/media', self.name.name)
        )

    class Meta:
        verbose_name_plural = '常用下载'


class Exercise(models.Model):
    title = models.CharField(max_length=50, verbose_name=u'视频标题')
    image = models.ImageField(
        upload_to='images/', verbose_name=u'视频封面图', null=True
    )
    description = models.CharField(max_length=255, verbose_name=u'视频描述')
    link = models.CharField(
        max_length=255, blank=True, null=False, verbose_name=u'视频链接'
    )
    submit_time = models.DateTimeField(auto_now_add=True, verbose_name=u"添加时间")

    def __unicode__(self):
        return '%s' % self.title

    class Meta:
        verbose_name_plural = '实践风采'


class Doc(models.Model):
    title = models.CharField(max_length=100, verbose_name=u'资料标题')
    name = models.FileField(
        upload_to='downloads/',
        max_length=255, blank=False
    )
    submit_time = models.DateTimeField(auto_now_add=True, verbose_name=u"添加时间")

    def __unicode__(self):
        return '%s' % self.name

    class Meta:
        verbose_name_plural = '支教资料库'


class Frame(models.Model):
    title = models.CharField(max_length=50, verbose_name=u'标题')
    content = models.TextField(verbose_name=u'正文内容')
    submit_time = models.DateTimeField(auto_now_add=True, verbose_name=u"添加时间")
    update_time = models.DateTimeField(auto_now_add=True, verbose_name=u"修改时间")
    view_count = models.IntegerField(default=0, verbose_name=u'浏览次数')

    def __unicode__(self):
        return '%s' % self.title

    def get_preview(self):
        return '</p>'.join(self.content.split('</p>')[:3]) + '</p>'

    def has_viewed(self):
        self.view_count += 1
        self.save()

    class Meta:
        verbose_name_plural = '课程框架'

apps/lessons/views.py
from django.shortcuts import render

# Create your views here.

apps/share/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from apps.utils.common import _paginator_result
from apps.share.models import ParentLessons, ChildLessons, Frame, Doc, Downloads, Exercise


def lesson(request):
    current_type = 'lesson'
    page = request.GET.get('page', 1)
    queryset = ParentLessons.objects.all().order_by('-submit_time')
    result = _paginator_result(queryset, page, per_page=9)
    page_max_show = 10
    resp = {
        'result': result,
        'current_type': current_type,
        'paginator': {
            'page_show_max': (int(page) + page_max_show / 2),
            'page_show_min': (int(page) - page_max_show / 2),
            'page': page,
        }
    }
    return render(request, 'share/lesson.html', resp)


def child_lesson(request, parent_id):
    current_type = 'lesson'
    page = request.GET.get('page', 1)
    queryset = ChildLessons.objects.filter(
        parent__id=parent_id
    ).order_by('-submit_time')
    result = _paginator_result(queryset, page, per_page=15)
    page_max_show = 10
    resp = {
        'result': result,
        'current_type': current_type,
        'paginator': {
            'page_show_max': (int(page) + page_max_show / 2),
            'page_show_min': (int(page) - page_max_show / 2),
            'page': page,
        }
    }
    return render(request, 'share/child_lesson.html', resp)


def exercise(request):
    current_type = 'exercise'
    page = request.GET.get('page', 1)
    queryset = Exercise.objects.all().order_by('-submit_time')
    result = _paginator_result(queryset, page, per_page=10)
    page_max_show = 10
    resp = {
        'result': result,
        'current_type': current_type,
        'paginator': {
            'page_show_max': (int(page) + page_max_show / 2),
            'page_show_min': (int(page) - page_max_show / 2),
            'page': page,
        }
    }
    return render(request, 'share/exercise.html', resp)


def doc(request):
    current_type = 'datum'
    current_inner = 'doc'
    page = request.GET.get('page', 1)
    queryset = Doc.objects.all().order_by('-submit_time')
    result = _paginator_result(queryset, page, per_page=10)
    page_max_show = 10
    resp = {
        'result': result,
        'current_type': current_type,
        'current_inner': current_inner,
        'paginator': {
            'page_show_max': (int(page) + page_max_show / 2),
            'page_show_min': (int(page) - page_max_show / 2),
            'page': page,
        }
    }
    return render(request, 'share/doc.html', resp)


def frame(request):
    current_type = 'datum'
    current_inner = 'frame'
    page = request.GET.get('page', 1)
    queryset = Frame.objects.all().order_by('-submit_time')
    result = _paginator_result(queryset, page, per_page=10)
    page_max_show = 10
    resp = {
        'result': result,
        'current_type': current_type,
        'current_inner': current_inner,
        'paginator': {
            'page_show_max': (int(page) + page_max_show / 2),
            'page_show_min': (int(page) - page_max_show / 2),
            'page': page,
        }
    }
    return render(request, 'share/frame.html', resp)


def article(request):
    current_type = 'datum'
    current_inner = 'frame'
    article_id = request.GET.get('id', None)
    article = get_object_or_404(Frame, id=article_id)
    article.has_viewed()
    resp = {
        'article': article,
        'current_type': current_type,
        'current_inner': current_inner,
    }
    return render(request, 'share/article.html', resp)


def downloads(request):
    current_type = 'downloads'
    page = request.GET.get('page', 1)
    queryset = Downloads.objects.all().order_by('-submit_time')
    result = _paginator_result(queryset, page, per_page=15)
    page_max_show = 10
    resp = {
        'result': result,
        'current_type': current_type,
        'paginator': {
            'page_show_max': (int(page) + page_max_show / 2),
            'page_show_min': (int(page) - page_max_show / 2),
            'page': page,
        }
    }
    return render(request, 'share/downloads.html', resp)

templates/share/article.html
{% extends 'global/base.html' %} 
{% block title %} 课程框架 {% endblock %}
{% block bodyClass %}
archive category category-activity category-5 group-blog
{% endblock %}
{% block content %}
<div id="content" class="site-content">
    <div id="primary" class="content-area">
        <main id="main" class="site-main" role="main">
            {% include 'global/share-page-header.html' %}
            <div class="container">
                <div id="archive-content" class="clear">
                    {% include 'global/share-sidebar-base.html' %}
                    <div class="page-content">
                        <article class="post-632 post type-post status-publish format-standard has-post-thumbnail hentry category-news">
                            <header class="entry-header">
                                <div class="entry-logo">
                                <i class="fa fa-newspaper-o"></i>
                                </div>
                                <h1 class="entry-title">
                                    <a href="#">{{article.title}}</a>
                                </h1>
                                <div class="entry-meta">
                                    <span class="posted-on">
                                        <i class="fa fa-calendar-o"></i>
                                        <time class="entry-date published">{{article.submit_time}}</time>
                                    </span>
                                    <span class="byline">
                                        <span class="author vcard">
                                            <i class="fa fa-folder-o"></i>
                                            课程框架
                                        </span>
                                    </span>
                                    <span class='views'>
                                        <i class='fa fa-eye'></i>
                                        {{article.view_count}}&nbsp;浏览
                                    </span>
                                </div>
                            </header>
                            <div class="entry-content">
                                {{article.content|safe}}
                            </div>
                            <footer class="entry-footer"></footer>
                        </article>
                        {% load duoshuo_tags %}
                        {% duoshuo_comments %}
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>

{% endblock %} {% block js %} 
{% endblock %}

templates/share/child_lesson.html
{% extends 'global/base.html' %} 
{% block title %} 网络课程 {% endblock %} 
{% block 3rd_css %}
<style type="text/css">
    img.wp-smiley,
    img.emoji {
        display: inline !important;
        border: none !important;
        box-shadow: none !important;
        height: 1em !important;
        width: 1em !important;
        margin: 0 .07em !important;
        vertical-align: -0.1em !important;
        background: none !important;
        padding: 0 !important;
    }

</style>
{% endblock %} 
{% block bodyClass %}
archive category category-activity category-5 group-blog
{% endblock %}
{% block content %}
<div id="content" class="site-content">
    <div id="primary" class="content-area">
        <main id="main" class="site-main" role="main">
            {% include 'global/share-page-header.html' %}
            <div class="container">
                <div id="archive-content" class="clear">
                    {% include 'global/share-sidebar-base.html' %}
                    <div class="page-content">    
                        <article class="schedule-list-box">
                            <!-- <header class="title">课程列表</header> -->
                            <a onclick="history.go(-1)" style="cursor: pointer;">返回上层</a>
                            <section class="content">
                                <p class="list-header">
                                    <span>名称</span>
                                </p>
                                <ul class="list">
                                    {% for p in result %}
                                    <li>
                                        <a href="{{p.link}}" target="_blank">
                                            {{p.title}}
                                        </a>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </section>
                        </article>
                        {% include 'global/paginator.html'%}
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>

{% endblock %} {% block js %} 
{% endblock %}

templates/share/doc.html
{% extends 'global/base.html' %} 
{% block title %} 主题教案 {% endblock %} 
{% block 3rd_css %}
<style type="text/css">
    img.wp-smiley,
    img.emoji {
        display: inline !important;
        border: none !important;
        box-shadow: none !important;
        height: 1em !important;
        width: 1em !important;
        margin: 0 .07em !important;
        vertical-align: -0.1em !important;
        background: none !important;
        padding: 0 !important;
    }

</style>
{% endblock %} 
{% block bodyClass %}
archive category category-activity category-5 group-blog
{% endblock %}
{% block content %}
<div id="content" class="site-content">
    <div id="primary" class="content-area">
        <main id="main" class="site-main" role="main">
            {% include 'global/share-page-header.html' %}
            <div class="container">
                <div id="archive-content" class="clear">
                    {% include 'global/share-sidebar-base.html' %}
                    <div class="page-content">    
                        <article class="schedule-list-box">
                            <header class="title">主题教案</header>
                            <section class="content">
                                <!-- <p class="list-header">
                                    <span>名称</span>
                                </p> -->
                                <ul class="list">
                                    {% for p in result %}
                                    <li>
                                        <a href="{{p.name.url}}">
                                            {{p.title}}&nbsp;&nbsp;[点击下载文件]
                                        </a>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </section>
                        </article>
                        {% include 'global/paginator.html'%}
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>

{% endblock %} {% block js %} 
{% endblock %}

templates/share/downloads.html
{% extends 'global/base.html' %} 
{% block title %} 常用下载 {% endblock %} 
{% block 3rd_css %}
<style type="text/css">
    img.wp-smiley,
    img.emoji {
        display: inline !important;
        border: none !important;
        box-shadow: none !important;
        height: 1em !important;
        width: 1em !important;
        margin: 0 .07em !important;
        vertical-align: -0.1em !important;
        background: none !important;
        padding: 0 !important;
    }

</style>
{% endblock %} 
{% block bodyClass %}
archive category category-activity category-5 group-blog
{% endblock %}
{% block content %}
<div id="content" class="site-content">
    <div id="primary" class="content-area">
        <main id="main" class="site-main" role="main">
            {% include 'global/share-page-header.html' %}
            <div class="container">
                <div id="archive-content" class="clear">
                    {% include 'global/share-sidebar-base.html' %}
                    <div class="page-content">    
                        <article class="schedule-list-box">
                            <header class="title">常用下载</header>
                            <section class="content">
                                <!-- <p class="list-header">
                                    <span>名称</span>
                                </p> -->
                                <ul class="list">
                                    {% for p in result %}
                                    <li>
                                        <a href="{{p.name.url}}" target="_blank">
                                            {{p.title}}&nbsp;&nbsp;[点击下载文件]
                                        </a>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </section>
                        </article>
                        {% include 'global/paginator.html'%}
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>

{% endblock %} {% block js %} 
{% endblock %}

templates/share/exercise.html
{% extends 'global/base.html' %} 
{% block title %} 实践风采 {% endblock %} 
{% block 3rd_css %}
<style type="text/css">
    img.wp-smiley,
    img.emoji {
        display: inline !important;
        border: none !important;
        box-shadow: none !important;
        height: 1em !important;
        width: 1em !important;
        margin: 0 .07em !important;
        vertical-align: -0.1em !important;
        background: none !important;
        padding: 0 !important;
    }

</style>
{% endblock %} 
{% block bodyClass %}
archive category category-activity category-5 group-blog
{% endblock %}
{% block content %}
<div id="content" class="site-content">
    <div id="primary" class="content-area">
        <main id="main" class="site-main" role="main">
            {% include 'global/share-page-header.html' %}
            <div class="container">
                <div id="archive-content" class="clear">
                    {% include 'global/share-sidebar-base.html' %}
                    <div class="page-content">    
                        <article class="box-list">
                        {% for p in result %}
                            <a class="box" href="{{p.link}}" target="_blank">
                                <p class="img-wrapper">
                                    <img src="{{p.image.url}}" style="height: 150px;width: 120px">
                                </p>
                                <div class="content">
                                <font style="font-size: 15px; color: #000"><strong>{{p.title|truncatechars:10}}</strong></font>
                                <br/>
                                <font style="font-size: 11px; color: #000">{{p.description|truncatechars:25}}</font>
                                <br/>
                                <font style="font-size: 12px; color: blue">[点击查看视频]</font>
                                </div>
                            </a>
                        {% endfor %}
                        </article>
                        {% include 'global/paginator.html'%}
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>

{% endblock %} {% block js %} 
{% endblock %}

templates/share/frame.html
{% extends 'global/base.html' %} 
{% block title %} 主题教案 {% endblock %} 
{% block 3rd_css %}
<style type="text/css">
    img.wp-smiley,
    img.emoji {
        display: inline !important;
        border: none !important;
        box-shadow: none !important;
        height: 1em !important;
        width: 1em !important;
        margin: 0 .07em !important;
        vertical-align: -0.1em !important;
        background: none !important;
        padding: 0 !important;
    }

</style>
{% endblock %} 
{% block bodyClass %}
archive category category-activity category-5 group-blog
{% endblock %}
{% block content %}
<div id="content" class="site-content">
    <div id="primary" class="content-area">
        <main id="main" class="site-main" role="main">
            {% include 'global/share-page-header.html' %}
            <div class="container">
                <div id="archive-content" class="clear">
                    {% include 'global/share-sidebar-base.html' %}
                    <div class="page-content">
                        {% for p in result %}
                        <article class="post-632 post type-post status-publish format-standard has-post-thumbnail hentry category-news">
                            <header class="entry-header">
                                <div class="entry-logo">
                                <i class="fa fa-newspaper-o"></i>
                                </div>
                                <h1 class="entry-title">
                                    <a href="/share/datum/frame/article?id={{p.id}}">{{p.title}}</a>
                                </h1>
                                <div class="entry-meta">
                                    <span class="posted-on">
                                        <i class="fa fa-calendar-o"></i>
                                        <time class="entry-date published">{{p.submit_time}}</time>
                                    </span>
                                    <span class="byline">
                                        <span class="author vcard">
                                            <i class="fa fa-folder-o"></i>
                                            课程框架
                                        </span>
                                    </span>
                                    <span class='views'>
                                        <i class='fa fa-eye'></i>
                                        {{p.view_count}}&nbsp;浏览
                                    </span>
                                </div>
                            </header>
                            <div class="entry-content">
                                {{p.content|truncatewords_html:50|safe}}
                                <p>
                                    <a href='/share/datum/frame/article?id={{p.id}}'  class="more-link">
                                    继续阅读
                                    <span class="screen-reader-text">&#8220;心随鸽舞，公益先行——白鸽青年志愿者协会2015-2016学年度全员大会圆满举办&#8221;</span>
                                    <span class="meta-nav">&rarr;</span>
                                    </a>
                                </p>
                            </div>
                            <footer class="entry-footer"></footer>
                        </article>
                        
                        {% endfor %}
                        {% include 'global/paginator.html'%}
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>

{% endblock %} {% block js %} 
{% endblock %}

templates/share/lesson.html
{% extends 'global/base.html' %} 
{% block title %} 网络课程 {% endblock %} 
{% block 3rd_css %}
<style type="text/css">
    img.wp-smiley,
    img.emoji {
        display: inline !important;
        border: none !important;
        box-shadow: none !important;
        height: 1em !important;
        width: 1em !important;
        margin: 0 .07em !important;
        vertical-align: -0.1em !important;
        background: none !important;
        padding: 0 !important;
    }

</style>
{% endblock %} 
{% block bodyClass %}
archive category category-activity category-5 group-blog
{% endblock %}
{% block content %}
<div id="content" class="site-content">
    <div id="primary" class="content-area">
        <main id="main" class="site-main" role="main">
            {% include 'global/share-page-header.html' %}
            <div class="container">
                <div id="archive-content" class="clear">
                    {% include 'global/share-sidebar-base.html' %}
                    <div class="page-content">    
                        <article class="box-list">
                        {% for p in result %}
                            <a class="box" href="/share/lesson/child/{{p.id}}">
                                <p class="img-wrapper">
                                    <img src="{{p.image.url}}" style="height: 150px;width: 120px">
                                </p>
                                <div class="content">
                                    <font style="font-size: 15px; color: #000"><strong>{{p.title|truncatechars:10}}</strong></font>
                                    <br/>
                                    <font style="font-size: 11px; color: #000">{{p.description|truncatechars:25}}</font>
                                    <br/>
                                    <font style="font-size: 12px; color: blue">{{p.childlessons_set.count}}门课 [点击查看]</font>
                                </div>
                            </a>
                        {% endfor %}
                        </article>
                        {% include 'global/paginator.html'%}
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>

{% endblock %} {% block js %} 
{% endblock %}